ChainID = '421611'
ChainType = 'arbitrum'
GasBumpThreshold = '0'
GasEstimatorMode = 'FixedPrice'
GasLimitDefault = 7000000
GasLimitTransfer = 800000
GasPriceDefault = '1000 gwei'
MaxGasPriceWei = '1000 gwei'
MinGasPriceWei = '1000 gwei'
LinkContractAddress = "0x615fBe6372676474d9e6933d310469c9b68e9726"
OCR.ContractConfirmations = 1

[BlockHistoryEstimator]
BlockHistorySize = 0

[HeadTracker]
BlockEmissionIdleWarningThreshold = '0'

[NodePool]
NoNewHeadsThreshold = '0'
