ChainID = '42161'
ChainType = 'arbitrum'
GasBumpThreshold = '0'
GasLimitDefault = 7000000
GasLimitTransfer = 800000
GasPriceDefault = '1000 gwei'
MaxGasPriceWei = '1000 gwei'
MinGasPriceWei = '1000 gwei'
GasEstimatorMode = 'FixedPrice'
LinkContractAddress = "0xf97f4df75117a78c1A5a0DBb814Af92458539FB4"
OCRContractConfirmations = 1

[BlockHistoryEstimator]
BlockHistorySize = 0
