ChainID = '42161'
ChainType = 'arbitrum'
LinkContractAddress = "0xf97f4df75117a78c1A5a0DBb814Af92458539FB4"
OCR.ContractConfirmations = 1

[GasEstimator]
Mode = 'FixedPrice'
BumpThreshold = '0'
LimitDefault = 7000000
LimitTransfer = 800000
PriceDefault = '1000 gwei'
PriceMaxWei = '1000 gwei'
PriceMinWei = '1000 gwei'

[GasEstimator.BlockHistory]
BlockHistorySize = 0

[HeadTracker]
BlockEmissionIdleWarningThreshold = '0'

[NodePool]
NoNewHeadsThreshold = '0'
