ChainID = '421611'
ChainType = 'arbitrum'
GasBumpThreshold = '0'
GasLimitDefault = 7000000
GasLimitTransfer = 800000
GasPriceDefault = '1000000000000'
MaxGasPriceWei = '1000000000000'
MinGasPriceWei = '1000000000000'
GasEstimatorMode = 'FixedPrice'
LinkContractAddress = "0x615fBe6372676474d9e6933d310469c9b68e9726"
OCRContractConfirmations = 1

[BlockHistoryEstimator]
BlockHistorySize = 0
