ChainID = '56'
TxResendAfterThreshold = '1m'
FinalityDepth = 50
GasBumpThreshold = 5
GasBumpWei = '5 gwei'
GasPriceDefault = '5 gwei'
LinkContractAddress = '0x404460C6A5EdE2D891e8297795264fDe62ADBB75'
LogPollInterval = '3s'
MinGasPriceWei = '1 gwei'
MinIncomingConfirmations = 3

[BalanceMonitor]
BlockDelay = 2

[BlockHistoryEstimator]
BlockDelay = 2
BlockHistorySize = 24

[HeadTracker]
BlockEmissionIdleWarningThreshold = '15s'
HistoryDepth = 100
SamplingInterval = '1s'

[NodePool]
NoNewHeadsThreshold = '30s'

[OCR]
DatabaseTimeout = '2s'
ContractTransmitterTransmitTimeout = '2s'
ObservationGracePeriod = '500ms'
