ChainID = '4'
LinkContractAddress = '0x01BE23585060835E02B77ef475b0Cc51aA1e0709'
MinimumContractPayment = '100000000000000000'

[BlockHistoryEstimator]
BatchSize = 4
BlockDelay = 1
BlockHistorySize = 4
TransactionPercentile = 50
