ChainID = '3'
EIP1559DynamicFees = true
LinkContractAddress = '0x20fE562d797A42Dcb3399062AE9546cd06f63280'
MinimumContractPayment = '100000000000000000'

[BlockHistoryEstimator]
BatchSize = 4
BlockDelay = 1
BlockHistorySize = 4
TransactionPercentile = 50
