BalanceMonitorEnabled = true
#BalanceMonitorBlockDelay = 1
EIP1559DynamicFees = false
FinalityDepth = 50
GasBumpPercent = 20
GasBumpThreshold = '3'
GasBumpTxDepth = 10
GasBumpWei = '5 gwei'
GasEstimatorMode = 'BlockHistory'
GasFeeCapDefault = '100 gwei'
GasLimitDefault = '500000'
GasLimitMultiplier = '1'
GasLimitTransfer = '21000'
GasPriceDefault = '20 gwei'
GasTipCapDefault = '1'
GasTipCapMinimum = '1'
LogBackfillBatchSize = 100
LogPollInterval = '15s'
MaxGasPriceWei = '100000 gwei'
MaxInFlightTransactions = 16
MaxQueuedTransactions = 250
MinGasPriceWei = '1 gwei'
MinIncomingConfirmations = 3
MinimumContractPayment = '.00001 link'
NonceAutoSync = true
OCRContractConfirmations = 4
OCRContractTransmitterTransmitTimeout = '10s'
OCRDatabaseTimeout = '10s'
OCRObservationGracePeriod = '1s'
RPCDefaultBatchSize = 100
TxReaperInterval = '1h0m0s'
TxReaperThreshold = '168h0m0s'
TxResendAfterThreshold = '1m0s'
UseForwarders = false

[BlockHistoryEstimator]
BatchSize = 4
BlockDelay = 1
BlockHistorySize = 8
TransactionPercentile = 60

[HeadTracker]
BlockEmissionIdleWarningThreshold = '1m0s'
HistoryDepth = 100
MaxBufferSize = 3
SamplingInterval = '1s'

[NodePool]
NoNewHeadsThreshold = '3m0s'
PollFailureThreshold = 5
PollInterval = '10s'
