ChainID = '4002'
GasPriceDefault = '15000000000'
MaxGasPriceWei = '200000000000000'
LinkContractAddress = '0xfaFedb041c0DD4fA2Dc0d87a6B0979Ee6FA7af5F'
MinIncomingConfirmations = 3
LogPollInterval = '1s'
