ChainID = '128'
#BalanceMonitorBlockDelay = 2
TxResendAfterThreshold = '1m'
FinalityDepth = 50
GasBumpThreshold = 5
GasBumpWei = '5 gwei'
GasPriceDefault = '5 gwei'
LinkContractAddress = '0x404460C6A5EdE2D891e8297795264fDe62ADBB75'
MinGasPriceWei = '1 gwei'
MinIncomingConfirmations = 3
OCRDatabaseTimeout = '2s'
OCRContractTransmitterTransmitTimeout = '2s'
OCRObservationGracePeriod = '500ms'
LogPollInterval = '3s'

[BlockHistoryEstimator]
BlockDelay = 2
BlockHistorySize = 24

[HeadTracker]
BlockEmissionIdleWarningThreshold = '15s'
HistoryDepth = 100
SamplingInterval = '1s'

