ChainID = '588'
ChainType = 'metis'
FinalityDepth = 1
GasBumpThreshold = 0
GasEstimatorMode = 'L2Suggested'
MinIncomingConfirmations = 1
MinGasPriceWei = '0'
OCR.ContractConfirmations = 1

[BalanceMonitor]
BlockDelay = 0

[BlockHistoryEstimator]
BlockHistorySize = 0

[HeadTracker]
BlockEmissionIdleWarningThreshold = '0'

[NodePool]
NoNewHeadsThreshold = '0'
