ChainID = '1088'
ChainType = 'metis'
FinalityDepth = 1
MinIncomingConfirmations = 1
OCR.ContractConfirmations = 1

[GasEstimator]
Mode = 'L2Suggested'
BumpThreshold = 0
PriceMinWei = '0'

[BalanceMonitor]
BlockDelay = 0

[GasEstimator.BlockHistory]
BlockHistorySize = 0

[HeadTracker]
BlockEmissionIdleWarningThreshold = '0'

[NodePool]
NoNewHeadsThreshold = '0'
