ChainID = '1088'
ChainType = 'metis'
#BalanceMonitorBlockDelay = 0
FinalityDepth = 1
GasBumpThreshold = 0
GasEstimatorMode = 'L2Suggested'
MinIncomingConfirmations = 1
MinGasPriceWei = '0'
OCRContractConfirmations = 1

[BlockHistoryEstimator]
BlockHistorySize = 0
