ChainID = '10'
ChainType = 'optimism'
FinalityDepth = 1
LinkContractAddress = '0x350a791Bfc2C21F9Ed5d10980Dad2e2638ffa7f6'
MinIncomingConfirmations = 1
OCR.ContractConfirmations = 1
TxResendAfterThreshold = '15s'

[BalanceMonitor]
BlockDelay = 0

[GasEstimator]
Mode = 'L2Suggested'
PriceMinWei = 0
BumpThreshold = '0'

[GasEstimator.BlockHistory]
BlockHistorySize = 0

[HeadTracker]
BlockEmissionIdleWarningThreshold = '0'
HistoryDepth = 10
SamplingInterval = '1s'

[NodePool]
NoNewHeadsThreshold = '0'
