ChainID = '137'
FinalityDepth = 500
GasBumpThreshold = 5
GasBumpWei = '20 gwei'
MaxQueuedTransactions = 5000
MaxGasPriceWei = '0.2 milli'
GasPriceDefault = '30 gwei'
MinGasPriceWei = '30 gwei'
TxResendAfterThreshold = '1m'
LinkContractAddress = '0xb0897686c545045aFc77CF20eC7A532E3120E0F1'
MinIncomingConfirmations = 5
LogPollInterval = '1s'

[BalanceMonitor]
BlockDelay = 13

[BlockHistoryEstimator]
BlockDelay = 10
BlockHistorySize = 24

[HeadTracker]
BlockEmissionIdleWarningThreshold = '15s'
HistoryDepth = 2000
SamplingInterval = '1s'
