ChainID = '137'
FinalityDepth = 500
LinkContractAddress = '0xb0897686c545045aFc77CF20eC7A532E3120E0F1'
LogPollInterval = '1s'
MaxQueuedTransactions = 5000
MinIncomingConfirmations = 5
TxResendAfterThreshold = '1m'

[BalanceMonitor]
BlockDelay = 13

[GasEstimator]
PriceDefault = '30 gwei'
PriceMaxWei = '0.2 milli'
PriceMinWei = '30 gwei'
BumpThreshold = 5
BumpWei = '20 gwei'

[GasEstimator.BlockHistory]
BlockDelay = 10
BlockHistorySize = 24

[HeadTracker]
BlockEmissionIdleWarningThreshold = '15s'
HistoryDepth = 2000
SamplingInterval = '1s'

[NodePool]
NoNewHeadsThreshold = '30s'
