ChainID = '30'
LinkContractAddress = '0x14AdaE34beF7ca957Ce2dDe5ADD97ea050123827'
LogPollInterval = '30s'
MinimumContractPayment = '0.001 link'

[GasEstimator]
PriceDefault = '50 mwei'
PriceMaxWei = '50 gwei'
PriceMinWei = 0
FeeCapDefault = '100 mwei'
