ChainID = '31'
GasPriceDefault = '50 mwei'
LinkContractAddress = '0x8bBbd80981FE76d44854D8DF305e8985c19f0e78'
MaxGasPriceWei = '50 gwei'
GasFeeCapDefault = '100 mwei'
MinGasPriceWei = 0
MinimumContractPayment = '1000000000000000'
LogPollInterval = '30s'
