ChainID = '31'
LinkContractAddress = '0x8bBbd80981FE76d44854D8DF305e8985c19f0e78'
MinimumContractPayment = '0.001 link'
LogPollInterval = '30s'

[GasEstimator]
PriceDefault = '50 mwei'
PriceMaxWei = '50 gwei'
PriceMinWei = 0
FeeCapDefault = '100 mwei'
