ChainID = '100'
ChainType = 'xdai'
GasBumpThreshold = '3'
GasPriceDefault = '1 gwei'
MinGasPriceWei = '1 gwei'
MaxGasPriceWei = '500 gwei'
LinkContractAddress = '0xE2e73A1c69ecF83F464EFCE6A5be353a37cA09b2'
LogPollInterval = '5s'
